name: release

on:
  push:
    branches:
      - 'master'
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

env:
  GO_VERSION: "1.22"

jobs:
  release:
    runs-on: personal
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Check & format go.mod
        run: go mod tidy

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check GoReleaser requirements
        uses: goreleaser/goreleaser-action@v6
        with:
          version: '~> v2'
          args: healthcheck

      - name: Validate .goreleaser.yaml
        uses: goreleaser/goreleaser-action@v6
        with:
          version: '~> v2'
          args: check

      - name: Release binaries
        if: success() && startsWith(github.ref, 'refs/tags/')
        uses: goreleaser/goreleaser-action@v6
        with:
          version: '~> v2'
          args: release --clean --parallelism 1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
